FROM node:alpine as builder
LABEL maintainer="jeremias.hillerberg@esss.se"
COPY package.json ./
WORKDIR /usr/src/app
COPY . .
RUN npm install
RUN npm install -g @angular/cli
RUN ng build --prod

FROM nginx:alpine
COPY ./config/nginx-custom.conf /etc/nginx/conf.d/default.conf
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
