FROM node:alpine
LABEL maintainer="jeremias.hillerberg@esss.se"
#ENV http_proxy "http://172.18.12.30:8123"
#ENV https_proxy $http_proxy
ENV no_proxy "localhost, 127.0.0.1"

#RUN npm config set proxy  $http_proxy
#RUN npm config set https-proxy  $http_proxy
RUN npm config set registry http://registry.npmjs.org/
RUN npm config set strict-ssl false
RUN npm install -g @angular/cli
COPY package.json /usr/src/app/package.json
WORKDIR /usr/src/app
RUN npm install
RUN npm install typescript@">=3.1.1 <3.3"
COPY . /usr/src/app
RUN ng build --prod
RUN npm install -g http-server
WORKDIR /usr/src/app/dist
EXPOSE 8080
CMD ["http-server", "-p","8080"]
