FROM node:alpine as builder
LABEL maintainer="jeremias.hillerberg@esss.se"
ENV no_proxy "localhost, 127.0.0.1"
ENV NGINX_RUNTIME 172.217.21.179
ENV NGINX_HOST ghs.googlehosted.com
RUN npm config set proxy  $http_proxy
RUN npm config set https-proxy  $http_proxy
RUN npm config set registry http://registry.npmjs.org/

RUN npm config set strict-ssl false
RUN npm config set unsafe-perm true

RUN npm install -g @angular/cli
RUN npm install nyc

COPY package.json /usr/src/app/package.json
WORKDIR /usr/src/app
RUN npm install
COPY . /usr/src/app
RUN ng build --configuration=gcloud

FROM nginx:alpine
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]

FROM node:11.14.0-alpine as builder
LABEL maintainer="jeremias.hillerberg@esss.se"

ENV http_proxy "http://192.168.1.1:8123"
ENV https_proxy $http_proxy
ENV no_proxy "localhost, 127.0.0.1"
ENV no_proxy 'cs-6000-devshell-vm-d60e19c3-7e57-490a-aafa-b5ab6b55f0a0'
RUN npm config set proxy  $http_proxy
RUN npm config set https-proxy  $http_proxy
RUN npm config set registry http://registry.npmjs.org/
RUN npm config set strict-ssl false
RUN npm install -g @angular/cli

COPY package.json /usr/src/app/package.json
WORKDIR /usr/src/app
RUN npm install typescript@">=3.1.1 <3.3"
RUN npm install
COPY . /usr/src/app
RUN ng build --configuration=esss

FROM nginx:alpine
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

ENV http_proxy "http://172.18.12.30:8123"
ENV https_proxy $http_proxy
ENV no_proxy "localhost, 127.0.0.1"

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]