export class Proposal {
	proposalId?: string;
	dateCreated?: string;
	experimentTitle?: string;
	briefSummary?: string;
	mainProposerFirstName?: string;
	mainProposerLastName?: string;
	mainProposerEmail?: string;
	mainProposerPhone?: string;
	mainProposerAffiliationName?: string;
	mainProposerAffiliationPhone?: string;
	mainProposerAffiliationStreet?: string;
	mainProposerAffiliationCity?: string;
	mainProposerAffiliationCountry?: string;
	coProposers?: [
		{
			firstName?: string;
			lastName?: string;
			email?: string;
			phone?: string;
			affiliation?: string;
		}
		];
	needByDate?: string;
	needByDateMotivation?: string;
	lab?: string;
	linksWithIndustry?: boolean;
	wantsCrystallization?: boolean;
	wantsBiomassDeuteration?: boolean;
	wantsProteinDeuteration?: boolean;
	wantsOtherDeuteration?: boolean;
	wantsChemicalDeuteration?: boolean;
	crystallization?: {
		moleculeName?: string;
		moleculeIdentifier?: string;
		molecularWeight?: string;
		oligomerizationState?: string;
		pbdId?: string;
		doi?: string;
		crystallizationRequirements?: string;
		crystallizationPrecipitantComposition?: string;
		previousCrystallizationExperience?: string;
		estimatedCrystallizationProductionTime?: string;
		typicalCrystalSize?: string;
		typicalYieldMgPerLiter?: string;
		storageConditions?: string;
		stability?: string;
		buffer?: string;
		levelOfDeuteration?: string;
		typicalProteinConcentrationUsed?: string;
		other?: string;
	};
	biomassDeuteration?: {
		organismProvidedByUser?: boolean;
		organismDetails?: string;
		amountNeeded?: string;
		amountNeededMotivation?: string;
		deuterationLevelRequired?: boolean;
		deuterationLevelMotivation?: string;
	};
	proteinDeuteration?: {
		moleculeName?: string;
		moleculeIdentifier?: string;
		molecularWeight?: string;
		oligomerizationState?: string;
		expressionRequirements?: string;
		moleculeOrigin?: string;
		expressionPlasmidProvidedByUser?: boolean;
		expressionPlasmidProvidedByUserDetails?: string;
		amountNeeded?: string;
		amountNeededMotivation?: string;
		deuterationLevelRequired?: string;
		deuterationLevelMotivation?: string;
		needsPurificationSupport?: string;
		hasDoneUnlabeledProteinExpression?: string;
		hasDonePurification?: boolean;
		hasProteinPurificationExperience?: string;
		proteinDeuterationResults?: string;
		other?: boolean;
	};
	bioSafety?: {
		bioSafetyContainmentLevel?: string;
		organismRisk?: boolean;
		organismRiskDetails?: string;
		other?: string;
	};
	chemicalDeuteration?: {
		moleculeName?: string;
		amount?: string;
		amountMotivation?: string;
		deuterationLocationAndPercentege?: string;
		deuterationLevelMotivation?: string;
		hasPreparedMolecule?: string;
		hasPreparedMoleculeProtocol?: string;
	};
	submitted?: boolean;
	other?: boolean;
	needByDateAttachment?: string;
	pbdIdReferenceAttachment?: string;
	organismReferenceAttachment?: string;
	needsPurificationSupportAttachment?: string;
	chemicalStructureAttachment?: string;
	proposalTemplate?: string;
	generatedProposal?: string;
	mergedProposal: string;
};
